--- #YAML:1.0
name:               Graph-Centrality-Pagerank
version:            1.05
abstract:           Computes pagerank of all nodes in a graph.
author:
    - Jeff Kubina (jeff.kubina@gmail.com)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:  1.14
    Graph:       0.91
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
